apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: simple-app
  labels:
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/part-of: simple-app
    apps.tanzu.vmware.com/has-tests: "true"
    apps.tanzu.vmware.com/language: java
spec:
  env:
    - name: SIMPLE_API_URL
      value: http://simple-api:8080
  params:
  - name: annotations
    value:
      autoscaling.knative.dev/minScale: "1"
  source:
    git:
      url: https://github.com/Simple-Org-123/simple-app.git
      ref:
        branch: main
